# Generated by Django 4.2.2 on 2023-06-13 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('pay', models.CharField(max_length=45)),
                ('requirement', models.TextField(max_length=2000)),
                ('date_due', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
