# Generated by Django 4.2.2 on 2023-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_logo',
            field=models.ImageField(blank=True, default='sabri-tuzcu-wunVFNvqhfE-unsplash.jpg', null=True, upload_to=''),
        ),
    ]
