# Generated by Django 4.2.2 on 2023-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='requirement',
            field=models.TextField(max_length=10000),
        ),
    ]
